version: '3.8'

services:
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
      - "3306:3306"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"
    restart: always
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: mysql.api.local
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.routers.mysql.rule=(`mysql.api.local`)"
      - "traefik.tcp.routers.mysql.entryPoints=mysql"
    restart: always

