version: '3.8'

services:
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
      - "3306:3306"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/services/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
    restart: always
  sql_handler:
    build:
       context: ./services/sql_handler
    command: gunicorn main:app --bind 0.0.0.0:5000 -k uvicorn.workers.UvicornWorker
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=PathPrefix(`/api/items/{item_id}`)"
  project_db:
    volumes:
      - ./mysql-dump/project:/docker-entrypoint-initdb.d
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: project
  irods_db:
    volumes:
      - ./mysql-dump/irods:/docker-entrypoint-initdb.d
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: irods
  owner_db:
    volumes:
      - ./mysql-dump/owner:/docker-entrypoint-initdb.d
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: owner
  analysis_db:
    volumes:
      - ./mysql-dump/analysis:/docker-entrypoint-initdb.d
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: analysis
