[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
    address = ":8080"
  [entryPoints.mysql]
    address = ":3306"

[api]
insecure = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"

[docker]
domain = "local"
watch = true
